Alpha module
hhhminme/kpu_sandol_team pull request #18
Opened 2021-08-08 15:37 UTC by Cycrypto

2021-08-08 15:43 UTC, Cycrypto commented on alphaSandol/lambda_module.py
> +    print(subway.subway())
삭제 예정

2021-08-08 15:43 UTC, Cycrypto commented on alphaSandol/Resource.py
> +        return "A"
삭제 예정

2021-08-11 03:09 UTC, DPS0340 requested changes
1차 리뷰입니다~

2021-08-11 03:09 UTC, DPS0340 commented on alphaSandol/Resource.py
> +    SANDOL_ACCESS_ID: list = ['d367f2ec55f41b4207156f4b8fce5ce885b05d8c3b238cf8861c55a9012f6f5895',
SANDOL_ACCESS_ID도 RESTAURANT_ACCESS_ID와 동일하게 이름이 key값인 dict로 변환하는게 어떨까요?

2021-08-11 03:09 UTC, DPS0340 commented on alphaSandol/return_type_generator.py
> +        return self.return_json
지금 로직상 basic_text dict에 text 값을 매핑하고, return_json을 반환하는 형태이니 자바의 setter 느낌을 살려서 set_text 정도의 메소드명을 가지는건 어떨까요?

2021-08-11 03:09 UTC, DPS0340 commented on alphaSandol/return_type_generator.py
> +        }
중괄호 초기화 자체가 shorthand notation이니 추가적인 타입 표시는 안해주셔도 괜찮을 것 같습니다!

2021-08-11 03:09 UTC, DPS0340 commented on alphaSandol/lambda_module.py
> +    def read_meal(self) -> GEN.is_Text:  # 학식 불러오기
메소드 값 자체를 반환 타입으로 보내고 있는 것으로 보여, 수정이 필요한 것 같습니다.

2021-08-11 03:09 UTC, DPS0340 commented on alphaSandol/lambda_module.py
> +    def read_meal(self) -> GEN.is_Text:  # 학식 불러오기
dict 정도로 바꾸면 될듯 하네요 ㅎ

2021-08-11 03:09 UTC, DPS0340 commented on alphaSandol/lambda_module.py
> +                    it.__next__()
저는 for loop이 진행될 때 이터레이터가 동작한다고 알고 있는데, 추가적인 이터레이터 변수 사용과 next 처리가 필요한가요? (저도 모르겠습니다.. ㅎ)

2021-08-11 03:09 UTC, DPS0340 commented on alphaSandol/lambda_module.py
> +    def weather(self, location: str = "정왕") -> GEN.is_Text:
타입 확인 해주세요~

2021-08-11 03:09 UTC, DPS0340 commented on alphaSandol/lambda_module.py
> +    def today_covid(self) -> GEN.is_Card:
타입 확인 부탁드려요~

2021-08-11 03:09 UTC, DPS0340 commented on alphaSandol/lambda_module.py
> +    def reset_meal(self, bot_id, date) -> GEN.is_Text:  # 학식 초기화
이쪽도 타입 확인 부탁드립니다.

2021-08-11 03:09 UTC, DPS0340 commented on alphaSandol/lambda_module.py
> +    def upload_meal(self, store_name, owner_id) -> GEN.is_Text:  # 학식 업로드
타입 확인 부탁드려요!

2021-08-12 09:33 UTC, Cycrypto commented on alphaSandol/lambda_module.py
> +                    it.__next__()
저도 그렇게 알고 있긴 한데, iteration 이 돌아가는 변수가 아니라 다른 변수의 iterator이 필요하다고 판단되어서 위 처럼 작성하였습니다

2021-08-14 03:21 UTC, Cycrypto reviewed
1차 리뷰 내용 반영해서 추가 수정완료하였습니다

2021-08-14 07:50 UTC, merged