Refactor
hhhminme/kpu_sandol_team pull request #22
Opened 2021-11-10 11:18 UTC by Cycrypto

1차 리펙토링 PR

2021-11-12 13:57 UTC, koptimizer reviewed
굿입니다요!

2021-11-12 13:57 UTC, koptimizer commented on alphaSandol/main.py
> +import alphaSandol as constant
alphaSandol에 대한 alias를 통일하는 것이 좋을 것 같습니다.
파일마다  constant 혹은 settings라는 키워드를 쓰신 것으로 보이는데, 기능적으로보면 settings이라는 단어가 더 잘 어울릴 것 같습니다.

2021-11-12 13:57 UTC, koptimizer commented on alphaSandol/main.py
> +        import weather
테스트 때문인지는 모르겠지만 각 모듈에 __main__ 블록이 달려있는 것으로 보입니다. 따라서 import 보단 from으로 함수나 클래스만 가져오는 것이 더 효과적이지 않을까 생각합니다.

2021-11-12 13:57 UTC, koptimizer commented on alphaSandol/announcement.py
> +        self.webLinkUrl = "https://www.kpu.ac.kr/contents/main/cor/noticehaksa.html"
self.webLinkUrl 변수도 다른 변수들과 똑같이 스네이크 표기로 통일해주시면 좋을 것 같습니다.
--> self.WEB_LINK_URL

2021-11-12 13:57 UTC, koptimizer commented on alphaSandol/covid.py
> +if __name__ == "__main__":
각 모듈마다 __main__블록이 있는 것은 테스트를 위함인가용?

2021-11-13 02:56 UTC, Cycrypto commented on alphaSandol/covid.py
> +if __name__ == "__main__":
네 맞습니다 Deploy하기 전에 `main.py`에 있는 아래쪽 main은 지울 예정이며 나머지는 테스트용으로 계속 둘 생각입니다

2021-11-13 03:43 UTC, Cycrypto commented
* 1차 코드 리뷰 수정
  * alias 수정
  * 표기법 수정
  * import 방식 수정

2021-11-13 05:46 UTC, hhhminme reviewed
코드리뷰라기보단 코드를 보면서 궁금한 점을 작성하였습니다. 중복되는 질문도 있어서 대표 질문만 답글 남겨주세요. 그리고 각 모듈을 파일로 구분한 이유에 대해 궁금합니다!

2021-11-13 05:46 UTC, hhhminme commented on alphaSandol/feedback.py
> +settings.DEBUG = True  # 디버그모드 트리거 -> boto3 테스트 대신 로컬로 테스트 할 때 사용
boto3 테스트랑 로컬테스트에 잘 몰라서 혹시 reply로 설명해주실 수 있나요?

2021-11-13 05:46 UTC, hhhminme commented on alphaSandol/feedback.py
> +                return settings.GEN.set_text(f"[File-Open-Error #113] 서버에서 피드백 파일을 불러오는 중 오류가 발생했어요\n{e}")
exception 발생 시 에러 코드가 있는데 몇번이 어떤 에러인지 따로 정리되어 있는게 있나요?

2021-11-13 05:46 UTC, hhhminme commented on alphaSandol/feedback.py
> +                return settings.GEN.set_text(f"[File-Open-Error #114] 파일 데이터를 삭제 중 오류가 발생했습니다{e}")
위의 질문가 동일합니다.

2021-11-13 05:46 UTC, hhhminme commented on alphaSandol/feedback.py
> +                return settings.GEN.set_text(f"[File-Open-Error #115] 파일을 서버에 업로드 하는 중 오류가 발생했습니다{e}")
우의 질문과 동일합니다.

2021-11-13 05:46 UTC, hhhminme commented on alphaSandol/restaurant.py
> +                    "[File-Open-Error #132] 파일을 여는 중 오류가 발생했어요.." + settings.IMOGE('emotion', 'sad') + str(e))
위의 exception 코드와 동일한 질문입니다.

2021-11-13 05:46 UTC, hhhminme commented on alphaSandol/restaurant.py
> +                    f"[File-Open-Error #124]파일을 저장소에 업로드하는 중 오류가 발생했습니다.{settings.IMOGE('emotion', 'sad')}\n{e}")
위의 질문과 동일한 질문 입니다.

2021-11-13 05:46 UTC, hhhminme commented on alphaSandol/restaurant.py
> +                f"[File-Open-Error #143]파일을 수정하는 중 오류가 발생했습니다.{settings.IMOGE('emotion', 'sad')}\n{e}")
위의 질문과 동일한 질문 입니다.

2021-11-13 05:46 UTC, hhhminme commented on alphaSandol/restaurant.py
> +                f"[File-Open-Error #124]파일을 저장소에 업로드하는 중 오류가 발생했습니다.{settings.IMOGE('emotion', 'sad')}\n{e}")
위의 질문과 동일한 질문 입니다.

2021-11-13 05:55 UTC, Cycrypto commented on alphaSandol/feedback.py
> +settings.DEBUG = True  # 디버그모드 트리거 -> boto3 테스트 대신 로컬로 테스트 할 때 사용
@hhhminme 
주석 설명이 조금 잘못되었네요.
bucket을 사용하는 함수에서 return 되는 json 형식이 valid 한지 이 전까지는 확인하기 어려웠습니다.
따라서 로컬에 같은 파일을 임시로 만들어 확인하는 방식으로 리펙토링했습니다.

이에대한 분기는 settings.DEBUG가 True일 때 실행되며 Deploy시 False로 만들어주는것이 "꼭" 필요합니다

2021-11-13 05:56 UTC, Cycrypto commented on alphaSandol/feedback.py
> +                return settings.GEN.set_text(f"[File-Open-Error #113] 서버에서 피드백 파일을 불러오는 중 오류가 발생했어요\n{e}")
에러코드는 코드 분리를 하기 전에 임의로 함수 위치에 따라 기준을 두고 정해두었었습니다.
이 부분도 추후에 다시 정립할 예정입니다

2021-11-13 06:05 UTC, hhhminme commented on alphaSandol/feedback.py
> +settings.DEBUG = True  # 디버그모드 트리거 -> boto3 테스트 대신 로컬로 테스트 할 때 사용
아하 그렇군요 감사합니다!

2021-11-13 06:05 UTC, hhhminme commented on alphaSandol/feedback.py
> +                return settings.GEN.set_text(f"[File-Open-Error #113] 서버에서 피드백 파일을 불러오는 중 오류가 발생했어요\n{e}")
넵 알겠습니다! 감사합니다😎

2021-11-13 07:20 UTC, DPS0340 requested changes
리팩토링 1차 코드 리뷰입니다~

2021-11-13 07:20 UTC, DPS0340 commented on alphaSandol/test_block.py
> +    ]
f-string과 list comprehension 조합해서 사용하는게 낫지 않을까요?

2021-11-13 07:20 UTC, DPS0340 commented on alphaSandol/covid.py
> +            return self.return_string
try블럭 최소화하고 except에서 바로 리턴해버리면 더 깔끔하지 않을까요? finally도 지우고 나머지 라인은 들여쓰기 한 블럭 당겨서 밑쪽에 넣구요~

2021-11-13 07:20 UTC, DPS0340 commented on alphaSandol/covid.py
> +            return self.return_string
아 AttributeError 문제가 있네요 흠 이건 url만 위로 올리는게 제일 나아보이기는 해요

2021-11-13 07:20 UTC, DPS0340 commented on alphaSandol/main.py
> +    elif func == "store_name" or func == "read_meal" or func == "reset_meal" or func == "time_meal" or "payment_meal":
elif func in ['store_name', 'read_meal'] 이런식으로 배열과 in을 같이 쓰면 깔끔해요~

2021-11-13 07:20 UTC, DPS0340 commented on alphaSandol/main.py
> +    # print(json.loads(func_call['body']))  # json 유니코드 -> UTF 확인용
pytest등 사용하여 __main__에서 빼내는게 좋지 않을까요?

2021-11-13 07:20 UTC, DPS0340 commented on alphaSandol/restaurant.py
> +        self.DINNER = 2
보조 클래스 만들어서 클래스 애트리뷰트로 쓰는게 좋을 것 같습니다

2021-11-13 07:20 UTC, DPS0340 commented on alphaSandol/main.py
> +        GEN().set_text(text=debugging("error", "main.function_handler", "전달된 파라미터가 잘못되었습니다."))
취향 차이가 있겠지만.. import 시점에 따라 오류가 생기는 경우가 아니면 import 구문은 모두 위로 올리는게 좋아 보입니다

2021-11-13 07:23 UTC, Cycrypto commented on alphaSandol/main.py
> +    # print(json.loads(func_call['body']))  # json 유니코드 -> UTF 확인용
pytest 라는건 처음 들어보네요 참고하겠습니다

2021-11-13 07:26 UTC, DPS0340 commented on alphaSandol/main.py
> +    # print(json.loads(func_call['body']))  # json 유니코드 -> UTF 확인용
구현은 파이썬 내장 unittest 모듈 쓰시는게 편할거예요~

2021-11-13 07:28 UTC, DPS0340 commented on alphaSandol/main.py
> +    # print(json.loads(func_call['body']))  # json 유니코드 -> UTF 확인용
아하 https://www.bangseongbeom.com/unittest-vs-pytest.html 이거 참고하시면 좋을거같아요! 저도 테스트는 최근에 시도해본것이라서.. 😅

2021-11-13 07:30 UTC, Cycrypto commented on alphaSandol/main.py
> +    elif func == "store_name" or func == "read_meal" or func == "reset_meal" or func == "time_meal" or "payment_meal":
아아 넵 전체적으로 어떤 말씀하시는지 알겠습니다 ㅎㅎ 곧 반영해서 다시 커밋할게요

2021-11-13 07:31 UTC, Cycrypto commented on alphaSandol/main.py
> +    # print(json.loads(func_call['body']))  # json 유니코드 -> UTF 확인용
새로운걸 알아갑니다 감사합니다

2021-11-16 02:41 UTC, Cycrypto commented on alphaSandol/test_block.py
> +    ]
무슨 뜻인지 이해가 잘 가지 않습니다...ㅎㅎ
조금 더 자세히 설명해주실수 있나요...?

2021-11-16 02:53 UTC, Cycrypto commented on alphaSandol/restaurant.py
> +        self.DINNER = 2
단순한 질문인데 그렇게 하면 어떤 장점이 있나요?

2021-11-16 17:29 UTC, DPS0340 commented on alphaSandol/restaurant.py
> +        self.DINNER = 2
재활용 가능하게 열거형처럼 Time 클래스를 만든다고 하면 기존의 클래스 영역이 아니라도 값을 사용할 수 있어요~
값과 로직을 분리시킬 수 있고 0, 1, 2 값은 사실 개발자 입장에서 생각할 필요가 없이 서로 다르기만 하면 되는 매직 넘버이니 사용하는 클래스에서는 구현을 알 필요가 없다고 생각하고 있어요. 간단히 말하면 추상화를 하는거죠

2021-11-16 17:31 UTC, DPS0340 commented on alphaSandol/test_block.py
> +    ]
넵! 
```python
Commerce_image = [
        f'https://raw.githubusercontent.com/hhhminme/kpu_sandol_team/main/commerce_img/commerce_test{x}.png' for x in range(1, 7)
]
```
이렇게 포매팅 문자열이랑 리스트에서 루프를 사용해서 축약하면 한 줄로 줄일 수 있어요

2021-11-22 14:13 UTC, merged